name: Build, Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Utiliser la version appropriée de .NET

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --output ./output -r win-x64 --self-contained  # Spécifiez le runtime approprié, par exemple, win-x64 pour Windows

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate version number
      id: version
      run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: List output directory contents
      run: ls -R ./output

    - name: Archive built files
      run: |
        cd output
        zip -r ../my-app-${{ env.VERSION }}.zip *
        cd ..
        echo "ARCHIVE=my-app-${{ env.VERSION }}.zip" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        body: |
          Changelog:
          - Première version
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ARCHIVE }}
        asset_name: ${{ env.ARCHIVE }}
        asset_content_type: application/zip
